version: '3.8'

services:
  autonomous_agent:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: autonomous_agent_devcontainer
    tty: true
    stdin_open: true
    ipc: host
    volumes:
      - ..:/root/autonomous_agent_ws
    environment:
      - ROS_DOMAIN_ID=0
