version: '3.8'

services:
  autonomous_agent:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: autonomous_agent_devcontainer
    tty: true
    stdin_open: true
    ipc: host
    volumes:
      - ..:/root/autonomous_agent_ws
    environment:
      - ROS_DOMAIN_ID=0
    depends_on:
      - novnc

  novnc:
    image: theasp/novnc:latest
    container_name: autonomous_agent_novnc
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080" # http://localhost:8080/vnc.html
